#version 460
#include "../../common/constants.glsl"
#include "../../common/normal_encoding.glsl"
#include "../../common/ddgi.glsl"
#include "../../common/reconstruction.glsl"
#include "../../common/util.glsl"
#include "../../common/viewport.glsl"

layout(local_size_x = TILE_SIZE, local_size_y = TILE_SIZE, local_size_z = 1) in;

restrict layout(std430, binding = 6) readonly buffer ProbeStateBuffer   { ProbeState probeStates[]; };
restrict layout(std430, binding = 7) readonly buffer DDGIVolumeBuffer   { DDGIVolume volume; };
restrict layout(std430, binding = 8) readonly buffer rendererDataBuffer { RendererData rendererData; };
restrict layout(std430, binding = 9) readonly buffer viewportDataBuffer { ViewportData viewportDataArr[]; };

uint GetGlobalProbeIndex(int probeIndex) {
    return volume.probeOffset + uint(probeIndex);
}

layout(r11f_g11f_b10f, binding = 0) uniform image2D outputImage;
layout(rgba16f, binding = 1) uniform image2D outputSurfaceImage;

layout (binding = 2) uniform sampler2D u_normalTexture;
layout (binding = 3) uniform sampler2D u_depthTexture;
layout (binding = 4) uniform sampler2DArray u_distanceAtlas;
layout (binding = 5) uniform sampler2DArray u_irradianceAtlas;

const float RTXGI_2PI = 6.2831853071795864;

const float encodingGamma = 5.0;

vec3 SampleIrradianceAtlasWithoutDistance(vec3 worldPos, vec3 normal) {
    if (any(lessThan(worldPos, volume.worldBoundsMin)) || any(greaterThan(worldPos, volume.worldBoundsMax))) {
        return vec3(0.0);
    }

    vec3 n = normalize(normal);
    vec3 biasedPos = worldPos + n * 0.1;

    ivec3 baseProbeCoords = DDGIGetBaseProbeGridCoords(biasedPos, volume);
    vec3 baseProbeWorldPosition = DDGIGetProbeBaseWorldPosition(baseProbeCoords, volume);
    vec3 alpha = clamp((biasedPos - baseProbeWorldPosition) / volume.probeSpacing, vec3(0.0), vec3(1.0));

    vec3 irradiance = vec3(0.0);
    float accumulatedWeights = 0.0;
    vec2 octantCoords = DDGIGetOctahedralCoordinates(n);

    for (int i = 0; i < 8; i++) {
        ivec3 offset = ivec3(i, i >> 1, i >> 2) & ivec3(1);
        ivec3 adjCoords = clamp(baseProbeCoords + offset, ivec3(0), volume.probeCounts - ivec3(1));
        int pIdx = DDGIGetProbeIndex(adjCoords, volume.probeCounts);

        if (!probeStates[GetGlobalProbeIndex(pIdx)].isActive) continue;

        vec3 probeUVW = DDGIGetProbeUV(pIdx, octantCoords, 6, volume);
        vec3 probeIrradiance = texture(u_irradianceAtlas, probeUVW).rgb;

        probeIrradiance = pow(max(vec3(0.0), probeIrradiance), vec3(encodingGamma * 0.5));

        vec3 trilinear = mix(1.0 - alpha, alpha, vec3(offset));
        float weight = trilinear.x * trilinear.y * trilinear.z;

        irradiance += probeIrradiance * weight;
        accumulatedWeights += weight;
    }

    if (accumulatedWeights == 0.0) return vec3(0.0);

    irradiance /= accumulatedWeights;
    irradiance *= irradiance; // Go back to linear
    irradiance *= RTXGI_2PI;

    return irradiance;
}

vec3 SampleIrradianceAtlas(vec3 worldPosition, vec3 normal, vec3 cameraPos) {
    if (any(lessThan(worldPosition, volume.worldBoundsMin)) || any(greaterThan(worldPosition, volume.worldBoundsMax))) {
        return vec3(0.0);
    }

    vec3 direction = normal;
    vec3 irradiance = vec3(0.0);
    float accumulatedWeights = 0.0;

    vec3 surfaceBias = DDGIGetSurfaceBias(worldPosition, normal, cameraPos);
    vec3 biasedWorldPosition = worldPosition + surfaceBias;

    ivec3 baseProbeCoords = DDGIGetBaseProbeGridCoords(biasedWorldPosition, volume);
    vec3 baseProbeWorldPosition = DDGIGetProbeBaseWorldPosition(baseProbeCoords, volume);
    vec3 gridSpaceDistance = (biasedWorldPosition - baseProbeWorldPosition);
    vec3 alpha = clamp((gridSpaceDistance / volume.probeSpacing), vec3(0.0), vec3(1.0));

    for (int probeIndex = 0; probeIndex < 8; probeIndex++) {
        ivec3 adjacentProbeOffset = ivec3(probeIndex, probeIndex >> 1, probeIndex >> 2) & ivec3(1);
        ivec3 adjacentProbeCoords = clamp(baseProbeCoords + adjacentProbeOffset, ivec3(0), volume.probeCounts - ivec3(1));
        int adjacentProbeIndex = DDGIGetProbeIndex(adjacentProbeCoords, volume.probeCounts);

        if (!probeStates[GetGlobalProbeIndex(adjacentProbeIndex)].isActive) continue;

        vec3 adjacentProbeWorldPosition = DDGIGetProbeWorldPosition(adjacentProbeCoords, volume, probeStates[GetGlobalProbeIndex(adjacentProbeIndex)]);
        vec3 worldPosToAdjProbe = normalize(adjacentProbeWorldPosition - worldPosition);
        vec3 biasedPosToAdjProbe = normalize(adjacentProbeWorldPosition - biasedWorldPosition);
        float biasedPosToAdjProbeDist = length(adjacentProbeWorldPosition - biasedWorldPosition);

        vec3 trilinear = max(vec3(0.001), mix(1.0 - alpha, alpha, vec3(adjacentProbeOffset)));
        float trilinearWeight = (trilinear.x * trilinear.y * trilinear.z);

        float weight = 1.0;
        float wrapShading = (dot(worldPosToAdjProbe, direction) + 1.0) * 0.5;
        weight *= (wrapShading * wrapShading) + 0.2;

        vec2 octantCoordsDist = DDGIGetOctahedralCoordinates(-biasedPosToAdjProbe);
        vec3 probeTextureUVDist = DDGIGetProbeUV(adjacentProbeIndex, octantCoordsDist, 14, volume);
        vec2 filteredDistance = 2.0 * texture(u_distanceAtlas, probeTextureUVDist).rg;

        float variance = abs((filteredDistance.x * filteredDistance.x) - filteredDistance.y);
        float chebyshevWeight = 1.0;
        if(biasedPosToAdjProbeDist > filteredDistance.x) {
            float v = biasedPosToAdjProbeDist - filteredDistance.x;
            chebyshevWeight = variance / (variance + (v * v) + 1e-5);
            chebyshevWeight = max((chebyshevWeight * chebyshevWeight * chebyshevWeight), 0.0);
        }

        weight *= max(0.05, chebyshevWeight);
        weight = max(0.000001, weight);

        const float crushThreshold = 0.2;
        if (weight < crushThreshold) {
            weight *= (weight * weight) * (1.0 / (crushThreshold * crushThreshold));
        }

        weight *= trilinearWeight;

        // Skip is possible
        if (weight < 0.001) continue;

        vec2 octantCoordsIrrad = DDGIGetOctahedralCoordinates(normal);
        vec3 probeTextureUVIrrad = DDGIGetProbeUV(adjacentProbeIndex, octantCoordsIrrad, 6, volume);
        vec3 probeIrradiance = texture(u_irradianceAtlas, probeTextureUVIrrad).rgb;

        probeIrradiance = pow(max(vec3(0.0), probeIrradiance), vec3(encodingGamma * 0.5));

        irradiance += (weight * probeIrradiance);
        accumulatedWeights += weight;
    }

    if(accumulatedWeights == 0.0) return vec3(0.0);

    irradiance /= accumulatedWeights;
    irradiance *= irradiance;
    irradiance *= RTXGI_2PI;

    return irradiance;
}

void main() {
    ivec2 px = ivec2(gl_GlobalInvocationID.xy);
    ivec2 outputImageSize = imageSize(outputImage);

    if (px.x >= outputImageSize.x || px.y >= outputImageSize.y) return;

    vec2 screenUV = ScreenUVFromPixel(px, outputImageSize);
    ivec2 gBufferSize = textureSize(u_normalTexture, 0);
    ivec2 inputCoords = clamp(ivec2(screenUV * vec2(gBufferSize)), ivec2(0), gBufferSize - ivec2(1));
    uint viewportIndex = ViewportIndexFromPixel(inputCoords, gBufferSize, rendererData.viewportLayout, vec2(rendererData.viewportSplitX, rendererData.viewportSplitY));
    ivec4 viewportRect = ivec4(viewportDataArr[viewportIndex].xOffset, viewportDataArr[viewportIndex].yOffset, viewportDataArr[viewportIndex].width, viewportDataArr[viewportIndex].height);
    mat4 inverseProjectionViewReverseZ = viewportDataArr[viewportIndex].inverseJitteredProjectionViewReverseZ;
    vec3 viewPos = viewportDataArr[viewportIndex].viewPos.xyz;
    vec2 viewportUV = ViewportUVFromPixel(inputCoords, gBufferSize, viewportRect);

    vec3 normal = DecodeOct(texelFetch(u_normalTexture, inputCoords, 0).rg);

    float normalLengthSq = dot(normal, normal);
    if (normalLengthSq < 0.0001) {
        imageStore(outputImage, px, vec4(0.0));
        imageStore(outputSurfaceImage, px, vec4(0.0));
        return;
    }

    normal *= inversesqrt(normalLengthSq);

    // Position from depth
    float depth = texelFetch(u_depthTexture, inputCoords, 0).r;
    vec3 worldPos = WorldPosFromDepth(viewportUV, depth, inverseProjectionViewReverseZ);

    if (any(lessThan(worldPos, volume.worldBoundsMin)) || any(greaterThan(worldPos, volume.worldBoundsMax))) {
        return;
    }

    vec3 finalIrradiance = SampleIrradianceAtlas(worldPos, normal, viewPos);
    finalIrradiance *= rendererData.irradianceDampening;

    //finalIrradiance = clamp(normal, vec3(0), vec3(1));
    //finalIrradiance = clamp(worldPos, 0, 1);

    imageStore(outputImage, px, vec4(finalIrradiance, 1.0));
    imageStore(outputSurfaceImage, px, vec4(normal, distance(worldPos, viewPos)));
    //imageStore(outputImage, pixelCoords, vec4(normal, 1.0));
    //imageStore(outputImage, px, vec4(viewportUV, 0, 1.0));
}
