#pragma once

namespace Unloved::Bible {

enum struct Item {
    UNDEFINED,
    AKS74U,
    GLOCK,
    GOLDEN_GLOCK,
    TOKAREV,
    KNIFE,
    REMINGTON_870,
    SPAS,
    SHOTGUN_SHELLS,
    BLACK_SKULL,
    SMALL_KEY,
    SMALL_KEY_SILVER,
    PILLS,
    P90
};

enum struct Weapon {
    UNDEFINED,
    KNIFE,
    GLOCK,
    GOLDEN_GLOCK,
    TOKAREV,
    REMINGTON_870,
    SPAS,
    AKS74U,
    P90
};

enum struct Ammo {
    UNDEFINED,
    GLOCK,
    TOKAREV,
    SHOTGUN_SHELLS,
    AKS74U,
    P90
};

enum struct AnimationProfile {
    DOBERMANN,
    RAT_KING_AKS74U,
    RAT_KING_GLOCK,
    RAT_KING_KNIFE,
    RAT_KING_P90,
    RAT_KING_REMINGTON870,
    RAT_KING_SPAS,
    RAT_KING_TOKAREV,
    SHARK,
    SNAKE,
    VIEW_WEAPON_AKS74U,
    VIEW_WEAPON_GLOCK,
    VIEW_WEAPON_KNIFE,
    VIEW_WEAPON_P90,
    VIEW_WEAPON_REMINGTON870,
    VIEW_WEAPON_SPAS,
    VIEW_WEAPON_TOKAREV,
    UNDEFINED
};

enum struct AnimationSlot {
    IDLE,
    WALK,
    IDLE_CROUCHING,
    WALK_CROUCHING,
    JUMP,
    DRAW,
    DRAW_FIRST,
    FIRE_1,
    FIRE_2,
    FIRE_3,
    RELOAD,
    RELOAD_EMPTY,
    ADS_IN,
    ADS_OUT,
    ADS_IDLE,
    ADS_WALK,
    ADS_FIRE_1,
    ADS_FIRE_2,
    ADS_FIRE_3,
    MELEE,
    DRY_FIRE,
    TOGGLE_AUTO,
    SHOTGUN_DRAW_PUMP,
    SHOTGUN_FIRE_NO_PUMP,
    SHOTGUN_RELOAD_START,
    SHOTGUN_RELOAD_END,
    SHOTGUN_RELOAD_END_PUMP,
    SHOTGUN_RELOAD_ONE_SHELL,
    SHOTGUN_RELOAD_TWO_SHELLS,
    DOBERMANN_LAY,
    DOBERMANN_LAY_TO_WALK,
    DOBERMANN_STRETCH_TO_LAY,
    DOBERMANN_WALK,
    SNAKE_SLITHER,
    SHARK_SWIM,
    SHARK_ATTACK_LEFT,
    SHARK_ATTACK_RIGHT,
    SHARK_DEATH,
    UNDEFINED
};

enum struct SkinnedModelPreset {
    CHARACTER_GLOCK,
    CHARACTER_GOLDEN_GLOCK,
    DOBERMANN,
    KANGAROO,
    RAT_KING,
    SHARK,
    SNAKE,
    TRAP_KING,
    UNISEX_GUY,
    VIEW_WEAPON_AKS74U,
    VIEW_WEAPON_GLOCK,
    VIEW_WEAPON_GOLDEN_GLOCK,
    VIEW_WEAPON_KNIFE,
    VIEW_WEAPON_P90,
    VIEW_WEAPON_REMINGTON_870,
    VIEW_WEAPON_SPAS,
    VIEW_WEAPON_TOKAREV,
    UNDEFINED
};

}
