#version 460
#include "../../common/OpenGL/GL_binding_indices.glsl"
#include "../../common/types.glsl"

layout(local_size_x = 256, local_size_y = 1, local_size_z = 1) in;

restrict layout(std430, binding = SSBO_IDX_PARTICLE_ADD_ADDITIONS) readonly buffer ParticleAdditionsBuffer {
    Particle particleAdditions[];
};

restrict layout(std430, binding = SSBO_IDX_PARTICLE_ADD_POOL) buffer ParticlePoolBuffer {
    Particle particlePool[];
};

restrict layout(std430, binding = SSBO_IDX_PARTICLE_ADD_COUNTER) buffer ParticleAdditionCounterBuffer {
    uint particleAdditionCounter;
};

uniform int u_newParticleCount;

#define MAX_GPU_PARTICLES 12000

void main() {
    uint poolIndex = gl_GlobalInvocationID.x;

    if (poolIndex >= MAX_GPU_PARTICLES) {
        return;
    }

    if (particlePool[poolIndex].exists != 0u) {
        return;
    }

    uint additionIndex = atomicAdd(particleAdditionCounter, 1u);

    if (additionIndex >= uint(u_newParticleCount)) {
        return;
    }

    Particle particle = particleAdditions[additionIndex];
    particle.exists = 1u;

    particlePool[poolIndex] = particle;
}
