#version 460
#extension GL_EXT_buffer_reference2 : require
#extension GL_EXT_scalar_block_layout : require
#extension GL_EXT_shader_explicit_arithmetic_types_int64 : require

#include "../common/Vulkan/VK_push_constants.glsl"

layout(local_size_x = 1, local_size_y = 1, local_size_z = 1) in;

layout(push_constant, scalar) uniform PushConstants {
    PushConstantsDDGIProbeDistanceDispatchArgs data;
} pc;

layout(buffer_reference, scalar) readonly buffer ProbeDistanceCounterBuffer { uint probeDistanceCounter; };
layout(buffer_reference, scalar) buffer DispatchIndirectCommandBuffer { uint num_groups_x; uint num_groups_y; uint num_groups_z; };

void main() {
    ProbeDistanceCounterBuffer counter = ProbeDistanceCounterBuffer(pc.data.probeDistanceCounterDeviceAddress);
    DispatchIndirectCommandBuffer command = DispatchIndirectCommandBuffer(pc.data.probeDistanceDispatchArgsDeviceAddress);
    command.num_groups_x = counter.probeDistanceCounter;
    command.num_groups_y = 1u;
    command.num_groups_z = 1u;
}
