#version 460
#extension GL_EXT_buffer_reference2 : require
#extension GL_EXT_nonuniform_qualifier : require
#extension GL_EXT_scalar_block_layout : require
#extension GL_EXT_shader_explicit_arithmetic_types_int64 : require

#include "../common/constants.glsl"
#include "../common/renderer_override_modes.glsl"
#include "../common/types.glsl"
#include "../common/viewport.glsl"
#include "../common/Vulkan/VK_push_constants.glsl"
#include "../common/Vulkan/VK_binding_indices.glsl"

layout(local_size_x = TILE_SIZE, local_size_y = TILE_SIZE, local_size_z = 1) in;

layout(set = 0, binding = DESC_IDX_STORAGE_IMAGES_RGBA16F, rgba16f) uniform image2D storageImagesRGBA16F[];

layout(push_constant, scalar) uniform PushConstants {
    PushConstantsDebugTileView data;
} pc;


shared vec3 sharedDebugOutputColor;

void main() {
    ivec2 texel = ivec2(gl_GlobalInvocationID.xy);
    ivec2 targetSize = imageSize(storageImagesRGBA16F[VULKAN_STORAGE_IMAGE_IDX_GBUFFER_LIGHTING]);

    if (texel.x >= targetSize.x || texel.y >= targetSize.y) return;

    TileLightsBuffer tileLights = pc.data.frame.tileLightBuffer;
    RendererDataBuffer rendererDataBuffer = pc.data.frame.rendererDataBuffer;

    RendererData rendererData = rendererDataBuffer.rendererData;
    uint viewportIndex = ViewportIndexFromPixel(texel, targetSize, rendererData.viewportLayout, vec2(rendererData.viewportSplitX, rendererData.viewportSplitY));
    bool viewportActive = IsViewportActive(viewportIndex, rendererData.activeViewportMask);

	if (gl_LocalInvocationIndex == 0) {
		uint tileIndex = gl_WorkGroupID.y * rendererData.tileCountX + gl_WorkGroupID.x;

        vec3 lightingColor = imageLoad(storageImagesRGBA16F[VULKAN_STORAGE_IMAGE_IDX_GBUFFER_LIGHTING], texel).rgb;

        float count = 0;

        // Tile lights
        if (rendererData.rendererOverrideState == OVERRIDE_TILE_HEATMAP_LIGHTS) {
			count = tileLights.tileLights[tileIndex].lightCount / 8.0;
		}
        if (rendererData.rendererOverrideState == OVERRIDE_TILE_HEATMAP_BLOOD_DECALS) {
			// TODO
		}
        if (rendererData.rendererOverrideState == OVERRIDE_TILE_HEATMAP_CHRISTMAS_LIGHTS) {
			// TODO
		}

		count = clamp(count, 0, 1);
		float level = count * 3.14159265/2;
		vec3 col;
		col.r = sin(level);
		col.g = sin(level * 2.0);
		col.b = cos(level);
		//sharedDebugOutputColor = lightingColor * 0.5 + col * col;
		sharedDebugOutputColor = (lightingColor * 0.1) + (col * col);

		if (tileLights.tileLights[tileIndex].lightCount == 0) {
			sharedDebugOutputColor = vec3(0,0,0);
		}
	}
	barrier();

    if (!viewportActive) {
        imageStore(storageImagesRGBA16F[VULKAN_STORAGE_IMAGE_IDX_GBUFFER_LIGHTING], texel, vec4(0.0, 0.0, 0.0, 1.0));
        return;
    }

    // Write tile color
    imageStore(storageImagesRGBA16F[VULKAN_STORAGE_IMAGE_IDX_GBUFFER_LIGHTING], texel, vec4(sharedDebugOutputColor, 1.0));

	// Lines
	if (gl_LocalInvocationIndex.x < TILE_SIZE || gl_LocalInvocationIndex.x % TILE_SIZE == 0 || gl_LocalInvocationIndex.x < TILE_SIZE || gl_LocalInvocationIndex.x % TILE_SIZE == 1) {
        imageStore(storageImagesRGBA16F[VULKAN_STORAGE_IMAGE_IDX_GBUFFER_LIGHTING], texel, vec4(0, 0, 0, 1));
	}
}
