#version 450 core
#include "../common/OpenGL/GL_binding_indices.glsl"
layout (local_size_x = 128, local_size_y = 1, local_size_z = 1) in;

struct Vertex {
    float position[3];
    float normal[3];
    float uv[2];
    float tangent[3];
};

struct VertexWeight {
    ivec4 boneID;
    vec4 weight;
};

struct SkinningJob {
    uint vertexCount;
    uint indexCount;
    uint sourceBaseVertex;
    uint sourceBaseIndex;

    uint sourceVertexWeightOffset;
    uint skinnedBaseVertex;
    uint skinningTransformOffset;
    uint padding;
};

struct SkinningMorphJob {
    uint morphTargetOffset;
    uint morphTargetCount;
    int rigidBoneIndex;
    uint padding;
};

struct SkinningMorphTarget {
    uint positionDeltaOffset;
    uint positionDeltaCount;
    uint normalDeltaOffset;
    uint normalDeltaCount;

    float currentWeight;
    float previousWeight;
    uint padding0;
    uint padding1;
};

struct MorphDelta {
    uint vertexIndex;
    float x;
    float y;
    float z;
};

struct SkinningDispatchGroup {
    uint jobIndex;
    uint vertexOffset;
    uint padding0;
    uint padding1;
};

struct PackedPosition {
    float x, y, z;
};

layout(std430, binding = SSBO_IDX_SKINNING_OUTPUT_VERTICES) buffer          outputVertexBuffer           { Vertex OutputVertexBuffer[]; };
layout(std430, binding = SSBO_IDX_SKINNING_INPUT_VERTICES) readonly buffer inputVertexBuffer            { Vertex InputVertexBuffer[]; };
layout(std140, binding = SSBO_IDX_SKINNING_ANIMATED_TRANSFORMS) readonly buffer transformsBuffer             { mat4 data[];} animatedTransforms;
layout(std430, binding = SSBO_IDX_SKINNING_WEIGHTS) readonly buffer weightsBuffer                { VertexWeight vertexWeights[]; };
layout(std430, binding = SSBO_IDX_SKINNING_JOBS) readonly buffer SkinningJobBuffer            { SkinningJob skinningJobs[]; };
layout(std430, binding = SSBO_IDX_SKINNING_DISPATCH_GROUPS) readonly buffer SkinningDispatchGroupBuffer  { SkinningDispatchGroup skinningDispatchGroups[]; };
layout(std140, binding = SSBO_IDX_SKINNING_PREVIOUS_TRANSFORMS) readonly buffer previousTransformsBuffer     { mat4 data[];} previousAnimatedTransforms;
layout(std430, binding = SSBO_IDX_SKINNING_PREVIOUS_POSITIONS) buffer          previousPositionBuffer       { PackedPosition previousSkinnedPositions[]; };
layout(std430, binding = SSBO_IDX_SKINNING_MORPH_JOBS) readonly buffer SkinningMorphJobBuffer              { SkinningMorphJob skinningMorphJobs[]; };
layout(std430, binding = SSBO_IDX_SKINNING_MORPH_TARGETS) readonly buffer SkinningMorphTargetBuffer        { SkinningMorphTarget skinningMorphTargets[]; };
layout(std430, binding = SSBO_IDX_SKINNING_MORPH_DELTAS) readonly buffer MorphDeltaBuffer                  { MorphDelta morphDeltas[]; };

vec3 FindMorphDelta(uint deltaOffset, uint deltaCount, uint vertexIndex) {
    uint left = 0;
    uint right = deltaCount;

    while (left < right) {
        uint middle = left + (right - left) / 2;
        uint middleVertexIndex = morphDeltas[deltaOffset + middle].vertexIndex;
        if (middleVertexIndex < vertexIndex) left = middle + 1;
        else right = middle;
    }

    if (left >= deltaCount) return vec3(0.0);
    MorphDelta delta = morphDeltas[deltaOffset + left];
    if (delta.vertexIndex != vertexIndex) return vec3(0.0);
    return vec3(delta.x, delta.y, delta.z);
}

void main() {
    SkinningDispatchGroup group = skinningDispatchGroups[gl_WorkGroupID.x];
    SkinningJob job = skinningJobs[group.jobIndex];
    SkinningMorphJob morphJob = skinningMorphJobs[group.jobIndex];

    // Bail if this workgroups local vertex will exceed the vertex count of the job
    uint localVertexIndex = group.vertexOffset + gl_LocalInvocationID.x;
    if (localVertexIndex >= job.vertexCount) return;

    uint sourceVertexIndex = job.sourceBaseVertex + localVertexIndex;
    uint skinnedVertexIndex = job.skinnedBaseVertex + localVertexIndex;

    Vertex vertexIn = InputVertexBuffer[sourceVertexIndex];

    vec4 vertexPosition = vec4(vertexIn.position[0], vertexIn.position[1], vertexIn.position[2], 1.0);
    vec4 previousVertexPosition = vertexPosition;
    vec3 vertexNormal = vec3(vertexIn.normal[0], vertexIn.normal[1], vertexIn.normal[2]);
    vec3 vertexTangent = vec3(vertexIn.tangent[0], vertexIn.tangent[1], vertexIn.tangent[2]);

    for (uint morphTargetIndex = 0; morphTargetIndex < morphJob.morphTargetCount; morphTargetIndex++) {
        SkinningMorphTarget morphTarget = skinningMorphTargets[morphJob.morphTargetOffset + morphTargetIndex];
        vec3 positionDelta = FindMorphDelta(morphTarget.positionDeltaOffset, morphTarget.positionDeltaCount, localVertexIndex);
        vec3 normalDelta = FindMorphDelta(morphTarget.normalDeltaOffset, morphTarget.normalDeltaCount, localVertexIndex);
        vertexPosition.xyz += positionDelta * morphTarget.currentWeight;
        previousVertexPosition.xyz += positionDelta * morphTarget.previousWeight;
        vertexNormal += normalDelta * morphTarget.currentWeight;
    }

    vertexNormal = normalize(vertexNormal);

    mat4 skinMat = mat4(0.0);
    mat4 previousSkinMat = mat4(0.0);

    if (morphJob.rigidBoneIndex >= 0) {
        uint skinningTransformIndex = uint(morphJob.rigidBoneIndex) + job.skinningTransformOffset;
        skinMat = animatedTransforms.data[skinningTransformIndex];
        previousSkinMat = previousAnimatedTransforms.data[skinningTransformIndex];
    }
    else {
        uint sourceVertexWeightIndex = job.sourceVertexWeightOffset + localVertexIndex;
        VertexWeight vertexWeight = vertexWeights[sourceVertexWeightIndex];
        ivec4 boneIDs = vertexWeight.boneID;
        vec4 weights = vertexWeight.weight;

        for(int i = 0; i < 4; i++) {
            float weight = weights[i];
            if (weight < 0.0001) continue;

            uint skinningTransformIndex = uint(boneIDs[i]) + job.skinningTransformOffset;
            skinMat += animatedTransforms.data[skinningTransformIndex] * weight;
            previousSkinMat += previousAnimatedTransforms.data[skinningTransformIndex] * weight;
        }
    }

    mat3 skinMat3 = mat3(skinMat);

    vec3 totalLocalPos = (skinMat * vertexPosition).xyz;
    vec3 previousLocalPos = (previousSkinMat * previousVertexPosition).xyz;
    vec3 totalNormal = normalize(skinMat3 * vertexNormal);

    vec3 totalTangent = normalize(skinMat3 * vertexTangent);
    totalTangent = normalize(totalTangent - totalNormal * dot(totalNormal, totalTangent));

    Vertex vertexOut;
    vertexOut.position[0] = totalLocalPos.x;
    vertexOut.position[1] = totalLocalPos.y;
    vertexOut.position[2] = totalLocalPos.z;

    vertexOut.normal[0] = totalNormal.x;
    vertexOut.normal[1] = totalNormal.y;
    vertexOut.normal[2] = totalNormal.z;

    vertexOut.tangent[0] = totalTangent.x;
    vertexOut.tangent[1] = totalTangent.y;
    vertexOut.tangent[2] = totalTangent.z;

    vertexOut.uv[0] = vertexIn.uv[0];
    vertexOut.uv[1] = vertexIn.uv[1];

    OutputVertexBuffer[skinnedVertexIndex] = vertexOut;
    previousSkinnedPositions[skinnedVertexIndex] = PackedPosition(previousLocalPos.x, previousLocalPos.y, previousLocalPos.z);
}
