#version 450
#include "../common/OpenGL/GL_binding_indices.glsl"
#include "../common/types.glsl"
#include "../common/util.glsl"
#include "../common/viewport.glsl"

layout(local_size_x = 8, local_size_y = 8, local_size_z = 1) in;

layout(r32f, binding = 0) uniform image2D ViewZImage;
layout(binding = 1) uniform sampler2D u_depthTexture;

readonly restrict layout(std430, binding = SSBO_IDX_RENDERER_DATA) buffer rendererDataBuffer { RendererData rendererData; };
readonly restrict layout(std430, binding = SSBO_IDX_VIEWPORT_DATA) buffer viewportDataBuffer { ViewportData viewportDataArr[]; };

void main() {
ivec2 px = ivec2(gl_GlobalInvocationID.xy);
    ivec2 outputImageSize = imageSize(ViewZImage);
    if (px.x >= outputImageSize.x || px.y >= outputImageSize.y) return;

    uint viewportIndex = ViewportIndexFromPixel(px, outputImageSize, rendererData.viewportLayout, vec2(rendererData.viewportSplitX, rendererData.viewportSplitY));
    ivec4 viewportRect = ivec4(viewportDataArr[viewportIndex].xOffset, viewportDataArr[viewportIndex].yOffset, viewportDataArr[viewportIndex].width, viewportDataArr[viewportIndex].height);
    mat4 inverseProjection = viewportDataArr[viewportIndex].inverseProjectionReverseZ;

    float depth = texelFetch(u_depthTexture, px, 0).r;
    vec2 ndcXY = ViewportNDCFromPixel(px, outputImageSize, viewportRect);
    vec4 ndcPos = vec4(ndcXY, depth, 1.0);
    vec4 viewPos = inverseProjection * ndcPos;
    float viewZ = viewPos.z / viewPos.w;

    imageStore(ViewZImage, px, vec4(viewZ, 0.0, 0.0, 1.0));
}
