#version 430 core
#include "../../common/OpenGL/GL_binding_indices.glsl"
#include "../../common/constants.glsl"
#include "../../common/ocean.glsl"

layout(local_size_x = 1, local_size_y = 1, local_size_z = 1) in;

uniform int u_displayMode = OCEAN_DISPLAY_MODE_COMBINED;
uniform float u_oceanOriginY;

layout(binding = 0) uniform sampler2D DisplacementTexture_band0;
layout(binding = 1) uniform sampler2D DisplacementTexture_band1;

struct OceanReadbackData {
    float heightPlayer0;
    float heightPlayer1;
    float heightPlayer2;
    float heightPlayer3;
};

layout (std430, binding = SSBO_IDX_OCEAN_POSITION_READBACK) restrict buffer Buffer { OceanReadbackData oceanReadbackData; };

uniform vec3 positionPlayer0;
uniform vec3 positionPlayer1;
uniform vec3 positionPlayer2;
uniform vec3 positionPlayer3;

float ComputeWaterHeight(vec3 queryPosition) {
    float height = SampleCombinedEstimatedOceanDisplacement(DisplacementTexture_band0, DisplacementTexture_band1, queryPosition.xz, u_displayMode).y;

    float waterHeight = (height) + u_oceanOriginY;

    return waterHeight;
}

void main() {
    oceanReadbackData.heightPlayer0 = ComputeWaterHeight(positionPlayer0);
    oceanReadbackData.heightPlayer1 = ComputeWaterHeight(positionPlayer1);
    oceanReadbackData.heightPlayer2 = ComputeWaterHeight(positionPlayer2);
    oceanReadbackData.heightPlayer3 = ComputeWaterHeight(positionPlayer3);
}
