#version 430 core
#include "../../common/OpenGL/GL_binding_indices.glsl"
#include "../../common/constants.glsl"
#include "../../common/types.glsl"
#include "../../common/util.glsl"
#include "../../common/viewport.glsl"

layout(local_size_x = 8, local_size_y = 8, local_size_z = 1) in;

layout (rgba16f, binding = 0) uniform image2D LightingImage;
layout (r8ui, binding = 1) readonly uniform uimage2D u_oceanFlagsImage;
layout (binding = 2) uniform sampler2D GaussianFinalLighting;
layout (binding = 3) uniform sampler2D WaterColorTexture;
layout (binding = 4) uniform sampler2D WaterDUDVTexture;

readonly restrict layout(std430, binding = SSBO_IDX_RENDERER_DATA) buffer rendererDataBuffer { RendererData  rendererData; };
readonly restrict layout(std430, binding = SSBO_IDX_VIEWPORT_DATA) buffer viewportDataBuffer { ViewportData  viewportDataArr[] ; };

uniform float u_time;

void main() {
    ivec2 px = ivec2(gl_GlobalInvocationID.xy);
    ivec2 outputImageSize = imageSize(LightingImage);

    // Bail if outta bounds
    if (px.x >= outputImageSize.x || px.y >= outputImageSize.y) return;
    
    uint flag = imageLoad(u_oceanFlagsImage, px).r;
    
    // Early out if pixel is the water surface or geometry above water surface
    if (flag == 0u || flag == 1u) return;

    uint viewportIndex = ViewportIndexFromPixel(px, outputImageSize, rendererData.viewportLayout, vec2(rendererData.viewportSplitX, rendererData.viewportSplitY));

    vec2 screenUV = (vec2(px) + 0.5) / vec2(outputImageSize);

    // Sample ocean lighting texture
    vec3 waterColor = texelFetch(WaterColorTexture, px, 0).rgb;

    // Get world ray
    ivec4 viewportRect = ivec4(viewportDataArr[viewportIndex].xOffset, viewportDataArr[viewportIndex].yOffset, viewportDataArr[viewportIndex].width, viewportDataArr[viewportIndex].height);
    mat4 inverseProjectionView = viewportDataArr[viewportIndex].inverseJitteredProjectionViewReverseZ;
    vec3 viewPos = viewportDataArr[viewportIndex].viewPos.xyz;
    vec3 rayDir = WorldRayFromPixel(px, outputImageSize, viewportRect, viewPos, inverseProjectionView);

    // calculate depth-based world ray fog
    vec3 down = vec3(0.0, -1.0, 0.0);
    float downwardness = clamp(dot(rayDir, down), 0.0, 1.0);
    float darkness = mix(1.0, 0.0, pow(downwardness, rendererData.oceanUnderwaterDarknessCurve));
    vec3 finalRayFog = rendererData.oceanUnderwaterRayFogColor.rgb * darkness * rendererData.oceanUnderwaterRayFogStrength;

    // calculate refraction distortion mapping
    float offsetX = fract(u_time * rendererData.oceanUnderwaterDistortionSpeed);
    vec2 uv_dudv = screenUV + vec2(offsetX, 0.0);
    vec2 distortion = texture(WaterDUDVTexture, uv_dudv).rg * 2.0 - 1.0;

    vec2 uv_refraction = screenUV + (distortion * rendererData.oceanUnderwaterDistortionStrength);
    uv_refraction = clamp(uv_refraction, vec2(0.0), vec2(1.0));

    vec3 refactoredFinalLighting = texture(GaussianFinalLighting, uv_refraction).rgb;

    // blend water tint into refracted lighting
    vec3 depthTint = refactoredFinalLighting * rendererData.oceanUnderwaterTint.rgb * rendererData.oceanUnderwaterDepthTintStrength;
    refactoredFinalLighting = mix(depthTint, refactoredFinalLighting, rendererData.oceanUnderwaterDepthTintOriginalWeight);

    // pixelUnderwater && oceanGeometry
    if (flag == 2u) {
        vec3 color = refactoredFinalLighting.rgb + (waterColor * waterColor * rendererData.oceanUnderwaterGeometryWaterColorSquaredStrength) + (waterColor * rendererData.oceanUnderwaterGeometryWaterColorStrength);
        color = mix(color, color * rendererData.oceanUnderwaterTint.rgb * rendererData.oceanUnderwaterTint.rgb, rendererData.oceanUnderwaterGeometryTintStrength);

        imageStore(LightingImage, px, vec4(color, 1.0));
    }
    else {
        // output final underwater color blend
        vec3 color = refactoredFinalLighting.rgb;
        color = mix(color, color * rendererData.oceanUnderwaterTint.rgb * rendererData.oceanUnderwaterTint.rgb, rendererData.oceanUnderwaterOpenWaterTintStrength);
        color -= finalRayFog;
        color *= rendererData.oceanUnderwaterOpenWaterBrightness;

        imageStore(LightingImage, px, vec4(color, 1.0));
    }
}
