#version 460

#include "../../common/OpenGL/GL_binding_indices.glsl"
#include "../../common/constants.glsl"
#include "../../common/renderer_override_modes.glsl"
#include "../../common/types.glsl"
#include "../../common/util.glsl"
#include "../../common/viewport.glsl"

layout(local_size_x = TILE_SIZE, local_size_y = TILE_SIZE, local_size_z = 1) in;

layout(rgba16f, binding = 0) uniform image2D u_outputImage;

uniform float u_viewportWidth;
uniform float u_viewportHeight;
uniform int u_tileXCount;
uniform int u_tileYCount;

shared vec3 sharedDebugOutputColor;

readonly restrict layout(std430, binding = SSBO_IDX_RENDERER_DATA) buffer rendererDataBuffer        { RendererData rendererData; };
readonly restrict layout(std430, binding = SSBO_IDX_LIGHTS) buffer lightsBuffer              { Light lights[]; };
readonly restrict layout(std430, binding = SSBO_IDX_DEBUG_TILES_TILE_LIGHTS) buffer tileLightsBuffer          { TileLights tileLights[]; };
readonly restrict layout(std430, binding = SSBO_IDX_DEBUG_TILES_TILE_BLOOD_DECALS) buffer tileBloodDecalsBuffer     { TileInstanceData tileBloodDecals[]; };
readonly restrict layout(std430, binding = SSBO_IDX_DEBUG_TILES_TILE_CHRISTMAS_LIGHTS) buffer tileChristmasLightsBuffer { TileInstanceData tileChristmasLights[]; };
readonly restrict layout(std430, binding = SSBO_IDX_DEBUG_TILES_TILE_SPOT_LIGHTS) buffer tileSpotLightsBuffer { TileSpotLights tileSpotLights[]; };

void main() {

	ivec2 px = ivec2(gl_GlobalInvocationID.xy);
    ivec2 outputImageSize = imageSize(u_outputImage);
    vec2 uv_screenspace = (vec2(px) + 0.5) / vec2(outputImageSize);

    // Don't process out of bounds pixels
    if (px.x >= outputImageSize.x || px.y >= outputImageSize.y) {
        return;
    }

    uint viewportIndex = ViewportIndexFromPixel(px, outputImageSize, rendererData.viewportLayout, vec2(rendererData.viewportSplitX, rendererData.viewportSplitY));
    bool viewportActive = IsViewportActive(viewportIndex, rendererData.activeViewportMask);

	const int tileSize = TILE_SIZE;
	vec2 viewportSize = vec2(u_viewportWidth, u_viewportHeight);
	vec2 uv = (vec2(px) + vec2(0.5)) / viewportSize;
	vec3 lightingColor = imageLoad(u_outputImage, px).rgb;

	// Heatmap
	if (gl_LocalInvocationIndex == 0) {
		uint tileIndex = gl_WorkGroupID.y * u_tileXCount + gl_WorkGroupID.x;

		// Lights
		uint selectedCount = 0u;

		if (rendererData.rendererOverrideState == OVERRIDE_TILE_HEATMAP_LIGHTS) {
			selectedCount = tileLights[tileIndex].lightCount;
		}
		if (rendererData.rendererOverrideState == OVERRIDE_TILE_HEATMAP_BLOOD_DECALS) {
			selectedCount = tileBloodDecals[tileIndex].count;
		}

		if (rendererData.rendererOverrideState == OVERRIDE_TILE_HEATMAP_CHRISTMAS_LIGHTS) {
			selectedCount = tileChristmasLights[tileIndex].count;
		}

		if (rendererData.rendererOverrideState == OVERRIDE_TILE_HEATMAP_SPOT_LIGHTS) {
			selectedCount = tileSpotLights[tileIndex].lightCount;
		}

		float count = float(selectedCount) / 8.0;
		count = clamp(count, 0, 1);
		float level = count * 3.14159265/2;
		vec3 col;
		col.r = sin(level);
		col.g = sin(level * 2.0);
		col.b = cos(level);
		sharedDebugOutputColor = lightingColor * 0.5 + col * col;
		sharedDebugOutputColor = (lightingColor * 0.1) + (col * col);
		if (selectedCount == 0u) {
			sharedDebugOutputColor = vec3(0,0,0);
		}
	}
	barrier();

    if (!viewportActive) {
        imageStore(u_outputImage, px, vec4(0.0, 0.0, 0.0, 1.0));
        return;
    }

	imageStore(u_outputImage, px, vec4(sharedDebugOutputColor, 1));

	// Lines
	if (gl_LocalInvocationIndex.x < TILE_SIZE || gl_LocalInvocationIndex.x % TILE_SIZE == 0 || gl_LocalInvocationIndex.x < TILE_SIZE || gl_LocalInvocationIndex.x % TILE_SIZE == 1) {
		imageStore(u_outputImage, px, vec4(0, 0, 0, 1));
	}
}
