#version 460 core

#include "../../common/taa_common.glsl"

layout(local_size_x = 8, local_size_y = 8, local_size_z = 1) in;

layout(binding = 0) uniform sampler2D u_taaBuffer;

layout(rgba16f, binding = 0) uniform writeonly image2D u_hdrOutput;
layout(rgba16f, binding = 1) uniform writeonly image2D u_historyOutput;

uniform ivec2 u_viewportOrigin;
uniform ivec2 u_viewportSize;

void main() {
    ivec2 localPixel = ivec2(gl_GlobalInvocationID.xy);
    ivec2 outputSize = imageSize(u_hdrOutput);

    if (any(greaterThanEqual(localPixel, u_viewportSize))) {
        return;
    }

    ivec2 pixel = u_viewportOrigin + localPixel;
    if (any(greaterThanEqual(pixel, outputSize))) return;

    vec3 center = texelFetch(u_taaBuffer, pixel, 0).rgb;

    imageStore(u_hdrOutput, pixel, vec4(TAAReinhardInverse(center), 1.0));
    imageStore(u_historyOutput, pixel, vec4(center, 1.0));
}
